[package]
name = "vad-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "vad_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
pyo3-log = "0.11"
numpy = "0.22"
ort = { version = "2.0.0-rc", features = ["ndarray"] }
rubato = "0.14"
ndarray = "0.17"
rustfft = "6"
