[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "vad-rs"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "vad_rs._core"